apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: mysqldb
spec:
  replicas: 1 
  selector:
    matchLabels:
      name: mysql
  template:
    metadata:
      labels:
        name: mysql
    spec:
      containers:
      - name: mysql
        image: 670435616773.dkr.ecr.us-east-1.amazonaws.com/assignment2-mysql:v1.0
        
