apiVersion: v1
kind: Pod
metadata:
  name: e-webapp
  labels:
    app: employees
spec:
  containers:
  - name: e-webapp
    image: 670435616773.dkr.ecr.us-east-1.amazonaws.com/assignment2-webapp:v1.0
    env:
      - name: DBHOST 
        value: 172.17.0.2
      - name: DBPORT
        value: "3306"
      - name: DBUSER
        value: root
      - name: DBPWD 
        value: pw
    ports: 
    - containerPort: 8080
      protocol: TCP

