apiVersion: v1
kind: Pod
metadata:
  name: webapp
spec:
  containers:
  - name: webapp
    image: 670435616773.dkr.ecr.us-east-1.amazonaws.com/assignment2-webapp:v1.0
    ports: 
    - containerPort: 8080
      protocol: TCP

